# Generated by Django 5.2.1 on 2025-05-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='job',
            name='keywords',
        ),
        migrations.AddField(
            model_name='job',
            name='keywords',
            field=models.ManyToManyField(related_name='jobs', to='job.keyword'),
        ),
    ]
