# Generated by Django 5.2.1 on 2025-05-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_keyword_remove_job_keywords_job_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='keywords',
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_years',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
