# Generated by Django 5.2.1 on 2025-05-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_remove_job_requirements_remove_job_work_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_location_type',
            field=models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('on_site', 'On Site')], default='remote', max_length=20),
            preserve_default=False,
        ),
    ]
